-- Ejecuta este script en Supabase SQL Editor.
-- MVP con Google Auth: cualquier usuario autenticado con Google puede leer,
-- crear, editar y eliminar registros. La app guarda correo/nombre en auditoria.

create table if not exists public.release_records (
  id bigint generated by default as identity primary key,
  release text not null default '',
  proyecto text not null default '',
  flujo text not null default '',
  en_base_a text not null default '',
  funcionalidades text not null default '',
  pase_a_produccion text not null default 'NO',
  fecha_de_pase date,
  activo text not null default 'SI',
  created_by_user_id uuid,
  created_by_email text not null default '',
  created_by_name text not null default '',
  updated_by_user_id uuid,
  updated_by_email text not null default '',
  updated_by_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.release_records
  add column if not exists created_by_user_id uuid,
  add column if not exists created_by_email text not null default '',
  add column if not exists created_by_name text not null default '',
  add column if not exists updated_by_user_id uuid,
  add column if not exists updated_by_email text not null default '',
  add column if not exists updated_by_name text not null default '';

create table if not exists public.portal_access_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text not null default '',
  full_name text not null default '',
  provider text not null default 'google',
  action text not null default 'login',
  user_agent text not null default '',
  accessed_at timestamptz not null default now()
);

create or replace function public.set_release_records_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_release_records_updated_at on public.release_records;

create trigger trg_release_records_updated_at
before update on public.release_records
for each row
execute function public.set_release_records_updated_at();

alter table public.release_records enable row level security;
alter table public.portal_access_logs enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.release_records to authenticated;
grant usage, select on sequence public.release_records_id_seq to authenticated;
grant select, insert on public.portal_access_logs to authenticated;
grant usage, select on sequence public.portal_access_logs_id_seq to authenticated;

drop policy if exists "release_records_select_public" on public.release_records;
drop policy if exists "release_records_insert_public" on public.release_records;
drop policy if exists "release_records_update_public" on public.release_records;
drop policy if exists "release_records_delete_public" on public.release_records;
drop policy if exists "portal_access_logs_select_authenticated" on public.portal_access_logs;
drop policy if exists "portal_access_logs_insert_own" on public.portal_access_logs;

create policy "release_records_select_public"
on public.release_records
for select
to authenticated
using (true);

create policy "release_records_insert_public"
on public.release_records
for insert
to authenticated
with check (true);

create policy "release_records_update_public"
on public.release_records
for update
to authenticated
using (true)
with check (true);

create policy "release_records_delete_public"
on public.release_records
for delete
to authenticated
using (true);

create policy "portal_access_logs_select_authenticated"
on public.portal_access_logs
for select
to authenticated
using (true);

create policy "portal_access_logs_insert_own"
on public.portal_access_logs
for insert
to authenticated
with check (auth.uid() = user_id);

create index if not exists idx_release_records_proyecto
on public.release_records (proyecto);

create index if not exists idx_release_records_pase_a_produccion
on public.release_records (pase_a_produccion);

create index if not exists idx_release_records_activo
on public.release_records (activo);

create index if not exists idx_release_records_created_by_email
on public.release_records (created_by_email);

create index if not exists idx_portal_access_logs_email
on public.portal_access_logs (email);

create index if not exists idx_portal_access_logs_accessed_at
on public.portal_access_logs (accessed_at desc);
