-- Ejecuta este script en Supabase SQL Editor.
-- MVP publico: cualquier usuario con el enlace de la app puede leer, crear,
-- editar y eliminar registros usando la anon key publicada en el frontend.

create table if not exists public.release_records (
  id bigint generated by default as identity primary key,
  release text not null default '',
  proyecto text not null default '',
  flujo text not null default '',
  en_base_a text not null default '',
  funcionalidades text not null default '',
  pase_a_produccion text not null default 'NO',
  fecha_de_pase date,
  activo text not null default 'SI',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_release_records_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_release_records_updated_at on public.release_records;

create trigger trg_release_records_updated_at
before update on public.release_records
for each row
execute function public.set_release_records_updated_at();

alter table public.release_records enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.release_records to anon, authenticated;
grant usage, select on sequence public.release_records_id_seq to anon, authenticated;

drop policy if exists "release_records_select_public" on public.release_records;
drop policy if exists "release_records_insert_public" on public.release_records;
drop policy if exists "release_records_update_public" on public.release_records;
drop policy if exists "release_records_delete_public" on public.release_records;

create policy "release_records_select_public"
on public.release_records
for select
to public
using (true);

create policy "release_records_insert_public"
on public.release_records
for insert
to public
with check (true);

create policy "release_records_update_public"
on public.release_records
for update
to public
using (true)
with check (true);

create policy "release_records_delete_public"
on public.release_records
for delete
to public
using (true);

create index if not exists idx_release_records_proyecto
on public.release_records (proyecto);

create index if not exists idx_release_records_pase_a_produccion
on public.release_records (pase_a_produccion);

create index if not exists idx_release_records_activo
on public.release_records (activo);
